"""
Festival Seed Data
==================
Contains 20+ festivals with complete cultural content.
Each festival includes: description, story, significance, traditions.
"""

FESTIVALS = [
    {
        "name": "Diwali",
        "slug": "diwali",
        "religion_culture": "Hindu",
        "typical_month": "October-November",
        "description": "Diwali, the Festival of Lights, is one of the most celebrated festivals in India. It symbolizes the victory of light over darkness, good over evil, and knowledge over ignorance.",
        "story_history": "Diwali commemorates the return of Lord Rama to Ayodhya after 14 years of exile and his victory over the demon king Ravana. The people of Ayodhya lit oil lamps (diyas) to welcome their beloved prince home, illuminating the entire kingdom. In South India, it celebrates Lord Krishna's victory over the demon Narakasura. For Jains, it marks the attainment of moksha by Lord Mahavira. Sikhs celebrate it as Bandi Chhor Divas, commemorating the release of Guru Hargobind Ji from prison.",
        "cultural_significance": "Diwali represents the triumph of righteousness and the dispelling of spiritual darkness. It's a time for family reunions, home renovations, new beginnings, and expressing gratitude. The festival spans five days, each with its own significance: Dhanteras (wealth), Naraka Chaturdashi (victory), Diwali (main celebration), Govardhan Puja (devotion), and Bhai Dooj (sibling love).",
        "traditions": "Cleaning and decorating homes, lighting diyas and candles, creating rangoli patterns, bursting fireworks, exchanging gifts and sweets, performing Lakshmi Puja for prosperity, wearing new clothes, and gathering with family for festive meals.",
        "seo_title": "Diwali Festival - Send Beautiful Diwali Wishes | FestWish",
        "seo_description": "Send personalized Diwali wishes to your loved ones. Create beautiful greeting cards for the Festival of Lights."
    },
    {
        "name": "Christmas",
        "slug": "christmas",
        "religion_culture": "Christian",
        "typical_month": "December",
        "description": "Christmas celebrates the birth of Jesus Christ and is observed worldwide on December 25th. It's a season of joy, giving, and togetherness that brings families and communities together.",
        "story_history": "Christmas commemorates the birth of Jesus Christ in Bethlehem over 2000 years ago. According to the Gospels, Mary and Joseph traveled to Bethlehem where Jesus was born in a manger. Shepherds and wise men came to honor the newborn. The date of December 25th was chosen in the 4th century, possibly to coincide with existing winter solstice celebrations. The holiday evolved to incorporate various traditions from different cultures.",
        "cultural_significance": "Christmas embodies themes of hope, love, peace, and generosity. It's a time to reflect on blessings, show kindness to others, and celebrate with loved ones. The holiday has both religious and secular significance, with traditions that bring people together regardless of faith.",
        "traditions": "Decorating Christmas trees, exchanging gifts, hanging stockings, singing carols, attending church services, preparing festive meals (turkey, ham, pudding), sending greeting cards, displaying nativity scenes, and the tradition of Santa Claus bringing gifts to children.",
        "seo_title": "Christmas Wishes - Send Merry Christmas Greetings | FestWish",
        "seo_description": "Create and send heartfelt Christmas wishes to friends and family. Beautiful Christmas cards for the holiday season."
    },
    {
        "name": "Eid al-Fitr",
        "slug": "eid-al-fitr",
        "religion_culture": "Islamic",
        "typical_month": "Lunar Calendar",
        "description": "Eid al-Fitr, the Festival of Breaking the Fast, marks the end of Ramadan, the holy month of fasting. It's a joyous celebration of spiritual achievement and community.",
        "story_history": "Eid al-Fitr was instituted by Prophet Muhammad after Muslims completed their first Ramadan fast. The festival celebrates the revelation of the Quran to Prophet Muhammad during Ramadan. It represents spiritual renewal and the rewards of a month of fasting, prayer, and self-reflection. The date changes each year according to the Islamic lunar calendar.",
        "cultural_significance": "Eid represents gratitude to Allah for providing strength during Ramadan, forgiveness, and new beginnings. It emphasizes charity (Zakat al-Fitr), family bonds, and community unity. The festival is a time of immense joy after a month of spiritual discipline.",
        "traditions": "Performing Eid prayers at mosques, giving Zakat al-Fitr (charity), wearing new clothes, visiting family and friends, preparing special dishes like sheer khurma and biryani, exchanging gifts (Eidi), and greeting with 'Eid Mubarak'.",
        "seo_title": "Eid al-Fitr Wishes - Send Eid Mubarak Greetings | FestWish",
        "seo_description": "Send beautiful Eid al-Fitr wishes to loved ones. Create personalized Eid Mubarak greeting cards."
    },
    {
        "name": "Holi",
        "slug": "holi",
        "religion_culture": "Hindu",
        "typical_month": "March",
        "description": "Holi, the Festival of Colors, is a vibrant spring festival celebrating love, joy, and the victory of good over evil. It's known for its playful throwing of colored powders.",
        "story_history": "Holi commemorates several legends. The primary story involves Prahlad, a devotee of Lord Vishnu, and his demoness aunt Holika who tried to kill him in a fire but was destroyed herself while Prahlad emerged unharmed. Another legend celebrates Radha and Krishna's divine love, where Krishna playfully applied colors to Radha. The festival also marks the arrival of spring and the end of winter.",
        "cultural_significance": "Holi represents the triumph of good over evil, forgiveness, renewal of relationships, and the joy of spring. It's a day to mend broken relationships, forget past grievances, and celebrate life's colors. Social barriers dissolve as people of all backgrounds play together.",
        "traditions": "Playing with colored powders (gulal) and water, lighting bonfires (Holika Dahan) on the eve, preparing special sweets like gujiya and malpua, drinking thandai and bhang, singing and dancing, and visiting friends and family.",
        "seo_title": "Holi Festival Wishes - Send Colorful Holi Greetings | FestWish",
        "seo_description": "Send vibrant Holi wishes to friends and family. Create beautiful greeting cards for the Festival of Colors."
    },
    {
        "name": "Chinese New Year",
        "slug": "chinese-new-year",
        "religion_culture": "Chinese",
        "typical_month": "January-February",
        "description": "Chinese New Year, also known as Spring Festival, is the most important traditional Chinese holiday. It celebrates the beginning of a new year on the Chinese lunar calendar.",
        "story_history": "The festival has over 4,000 years of history. Legend tells of the monster Nian who attacked villagers until they discovered it feared the color red, loud noises, and fire. The traditions of red decorations, firecrackers, and lanterns emerged from this story. The celebration typically lasts 15 days, ending with the Lantern Festival.",
        "cultural_significance": "Chinese New Year represents renewal, family reunion, and honoring ancestors. It's a time to wish for prosperity, good health, and happiness in the coming year. Each year is associated with one of 12 zodiac animals, influencing the year's characteristics.",
        "traditions": "Family reunion dinners, giving red envelopes (hongbao) with money, displaying red decorations, setting off firecrackers, dragon and lion dances, cleaning homes before the new year, preparing special foods like dumplings and fish, and visiting temples.",
        "seo_title": "Chinese New Year Wishes - Send Lunar New Year Greetings | FestWish",
        "seo_description": "Send auspicious Chinese New Year wishes. Create beautiful greeting cards for the Spring Festival."
    },
    {
        "name": "Thanksgiving",
        "slug": "thanksgiving",
        "religion_culture": "American",
        "typical_month": "November",
        "description": "Thanksgiving is a national holiday celebrating gratitude for the harvest and blessings of the past year. It's a day for family gatherings and giving thanks.",
        "story_history": "The first Thanksgiving is traditionally attributed to the 1621 harvest celebration by the Pilgrims and Wampanoag Native Americans in Plymouth, Massachusetts. After a harsh winter and successful harvest, they gathered for a three-day feast. Abraham Lincoln proclaimed Thanksgiving a national holiday in 1863. Canada celebrates Thanksgiving in October.",
        "cultural_significance": "Thanksgiving represents gratitude, family togetherness, and reflection on life's blessings. It's a time to appreciate loved ones, share abundance with those in need, and pause from daily routines to give thanks.",
        "traditions": "Preparing turkey dinners with stuffing, cranberry sauce, and pumpkin pie; watching football; the Macy's Thanksgiving Day Parade; saying grace before meals; volunteering at food banks; and spending quality time with family.",
        "seo_title": "Thanksgiving Wishes - Send Grateful Greetings | FestWish",
        "seo_description": "Send heartfelt Thanksgiving wishes to loved ones. Create beautiful cards expressing gratitude."
    },
    {
        "name": "Easter",
        "slug": "easter",
        "religion_culture": "Christian",
        "typical_month": "March-April",
        "description": "Easter celebrates the resurrection of Jesus Christ from the dead, as described in the New Testament. It's the most important feast in the Christian calendar.",
        "story_history": "According to the Gospels, Jesus was crucified on Good Friday and rose from the dead on the third day, Easter Sunday. This resurrection is the foundation of Christian faith, symbolizing victory over death and the promise of eternal life. The date varies each year, calculated as the first Sunday after the first full moon following the spring equinox.",
        "cultural_significance": "Easter represents hope, renewal, new life, and the triumph of life over death. For Christians, it's a celebration of salvation and redemption. The spring timing connects it to themes of rebirth in nature.",
        "traditions": "Attending Easter church services, Easter egg hunts, decorating Easter eggs, the Easter Bunny bringing baskets of treats, Easter parades, preparing lamb or ham dinners, Hot Cross Buns, and wearing new spring clothes.",
        "seo_title": "Easter Wishes - Send Happy Easter Greetings | FestWish",
        "seo_description": "Send joyful Easter wishes to family and friends. Create beautiful Easter greeting cards."
    },
    {
        "name": "Navratri",
        "slug": "navratri",
        "religion_culture": "Hindu",
        "typical_month": "September-October",
        "description": "Navratri is a nine-night festival dedicated to the worship of Goddess Durga and her nine forms. It celebrates the victory of good over evil and divine feminine energy.",
        "story_history": "Navratri commemorates Goddess Durga's battle with the buffalo demon Mahishasura, which lasted nine nights and ten days. Each day honors a different form of the goddess: Shailaputri, Brahmacharini, Chandraghanta, Kushmanda, Skandamata, Katyayani, Kaalratri, Mahagauri, and Siddhidatri. The tenth day, Vijayadashami, celebrates her victory.",
        "cultural_significance": "Navratri represents the worship of Shakti (divine feminine power), inner purification, and spiritual awakening. It's a time for fasting, prayer, and invoking the goddess's blessings for strength, wisdom, and protection.",
        "traditions": "Fasting during the nine days, performing Garba and Dandiya Raas dances, setting up Golu (doll displays), worshipping Durga with elaborate pujas, wearing different colored clothes each day, and preparing special sattvic food.",
        "seo_title": "Navratri Wishes - Send Durga Puja Greetings | FestWish",
        "seo_description": "Send divine Navratri wishes to loved ones. Create beautiful greeting cards for the nine nights of worship."
    },
    {
        "name": "Hanukkah",
        "slug": "hanukkah",
        "religion_culture": "Jewish",
        "typical_month": "November-December",
        "description": "Hanukkah, the Festival of Lights, is an eight-day Jewish celebration commemorating the rededication of the Second Temple in Jerusalem and the miracle of the oil.",
        "story_history": "Hanukkah recalls the Maccabean Revolt (167-160 BCE) when Jews reclaimed the Temple from Seleucid rule. Upon rededication, they found only enough consecrated oil to light the Temple's menorah for one day, but miraculously it burned for eight days until new oil could be prepared. This miracle inspired the eight-day celebration.",
        "cultural_significance": "Hanukkah represents religious freedom, perseverance, and divine miracles. It's a celebration of Jewish identity, the triumph of faith over oppression, and the endurance of hope even in dark times.",
        "traditions": "Lighting the menorah (hanukkiah) adding one candle each night, playing dreidel, eating foods fried in oil like latkes and sufganiyot (jelly donuts), giving gelt (money or chocolate coins), exchanging gifts, and singing Hanukkah songs.",
        "seo_title": "Hanukkah Wishes - Send Happy Chanukah Greetings | FestWish",
        "seo_description": "Send warm Hanukkah wishes to family and friends. Create beautiful Festival of Lights greeting cards."
    },
    {
        "name": "New Year",
        "slug": "new-year",
        "religion_culture": "Global",
        "typical_month": "January",
        "description": "New Year's Day marks the beginning of the calendar year on January 1st. It's celebrated worldwide with fireworks, parties, and resolutions for the year ahead.",
        "story_history": "The celebration of New Year dates back thousands of years. The Romans dedicated January 1st to Janus, the god of beginnings and transitions, whose two faces looked to the past and future. The Gregorian calendar, introduced in 1582, established January 1st as the official start of the year in the Western world. Different cultures celebrate new years at different times.",
        "cultural_significance": "New Year represents fresh starts, hope, and the opportunity for positive change. It's a time to reflect on the past year's experiences, set goals for the future, and celebrate with loved ones.",
        "traditions": "Midnight countdown and fireworks, New Year's Eve parties, making resolutions, watching the ball drop (Times Square), singing Auld Lang Syne, toasting with champagne, and first-footing in Scotland.",
        "seo_title": "New Year Wishes - Send Happy New Year Greetings | FestWish",
        "seo_description": "Send inspiring New Year wishes to loved ones. Create beautiful cards for the year ahead."
    },
    {
        "name": "Raksha Bandhan",
        "slug": "raksha-bandhan",
        "religion_culture": "Hindu",
        "typical_month": "August",
        "description": "Raksha Bandhan is a festival celebrating the bond between brothers and sisters. Sisters tie a protective thread (rakhi) on their brothers' wrists.",
        "story_history": "Several legends are associated with Raksha Bandhan. One tells of Draupadi tying a piece of her sari on Lord Krishna's wrist, who then protected her. Another involves the god of death, Yama, being bound by a rakhi from his sister Yamuna, granting her immortality. Historically, Rani Karnavati sent a rakhi to Emperor Humayun seeking protection for her kingdom.",
        "cultural_significance": "Raksha Bandhan represents the sacred bond between siblings, the brother's promise to protect his sister, and the sister's prayers for her brother's well-being. It extends beyond biological siblings to honor any protective relationship.",
        "traditions": "Sisters tying rakhis on brothers' wrists, brothers giving gifts and money to sisters, performing aarti, exchanging sweets, family gatherings, and sisters fasting until they tie the rakhi.",
        "seo_title": "Raksha Bandhan Wishes - Send Rakhi Greetings | FestWish",
        "seo_description": "Send loving Raksha Bandhan wishes to siblings. Create beautiful rakhi greeting cards."
    },
    {
        "name": "Valentine's Day",
        "slug": "valentines-day",
        "religion_culture": "Global",
        "typical_month": "February",
        "description": "Valentine's Day is a celebration of love and affection observed on February 14th. It's a day to express love to romantic partners, friends, and family.",
        "story_history": "Valentine's Day is named after Saint Valentine, a Christian martyr from 3rd century Rome. Legend says he performed weddings for soldiers forbidden to marry and ministered to persecuted Christians. He was executed on February 14th. The day became associated with romantic love in the Middle Ages when Geoffrey Chaucer and others wrote about it in literature.",
        "cultural_significance": "Valentine's Day represents romantic love, appreciation for loved ones, and the expression of affection. While traditionally focused on romantic relationships, it has expanded to celebrate all forms of love including friendship and family bonds.",
        "traditions": "Exchanging Valentine's cards, giving flowers (especially red roses), chocolates and gifts, romantic dinners, marriage proposals, expressing love to friends ('Galentine's Day'), and random acts of kindness.",
        "seo_title": "Valentine's Day Wishes - Send Love Messages | FestWish",
        "seo_description": "Send romantic Valentine's Day wishes to your special someone. Create beautiful love greeting cards."
    },
    {
        "name": "Durga Puja",
        "slug": "durga-puja",
        "religion_culture": "Hindu",
        "typical_month": "September-October",
        "description": "Durga Puja is a grand festival honoring Goddess Durga's victory over the demon Mahishasura. Celebrated with elaborate pandals, artistic idols, and cultural performances.",
        "story_history": "The festival commemorates Goddess Durga's epic battle against the buffalo demon Mahishasura, who had become invincible and terrorized the heavens. The gods combined their powers to create Durga, who fought Mahishasura for nine nights and slew him on the tenth day. This victory of divine feminine power over evil is celebrated annually.",
        "cultural_significance": "Durga Puja represents the triumph of good over evil and celebrates divine feminine energy (Shakti). It's particularly significant in Bengal, where it's the biggest annual festival marking homecoming, artistic expression, and community bonding.",
        "traditions": "Building elaborate decorated pandals (temporary structures), commissioning artistic clay idols, performing dhunuchi dance with incense, eating khichuri and bhog, wearing new clothes, visiting pandals, and immersing idols in water on Vijaya Dashami.",
        "seo_title": "Durga Puja Wishes - Send Puja Greetings | FestWish",
        "seo_description": "Send auspicious Durga Puja wishes. Create beautiful greeting cards for Maa Durga's festival."
    },
    {
        "name": "Ganesh Chaturthi",
        "slug": "ganesh-chaturthi",
        "religion_culture": "Hindu",
        "typical_month": "August-September",
        "description": "Ganesh Chaturthi celebrates the birth of Lord Ganesha, the elephant-headed god of wisdom, prosperity, and new beginnings. Homes and public spaces install Ganesha idols for 10 days.",
        "story_history": "According to mythology, Goddess Parvati created Ganesha from sandalwood paste to guard her privacy. When Lord Shiva returned and was stopped by Ganesha, he beheaded him in anger. To console Parvati, Shiva replaced Ganesha's head with that of an elephant and granted him the status of being worshipped first among all gods.",
        "cultural_significance": "Lord Ganesha is the remover of obstacles and the god of beginnings. His festival marks the importance of wisdom, perseverance, and auspicious starts. He's invoked before any new venture, journey, or important event.",
        "traditions": "Installing Ganesha idols at homes and public pandals, offering modak (sweet dumplings), performing aarti, reciting Ganesha mantras, decorating with flowers, and the grand visarjan (immersion) procession with music and dancing.",
        "seo_title": "Ganesh Chaturthi Wishes - Send Ganpati Greetings | FestWish",
        "seo_description": "Send blessed Ganesh Chaturthi wishes. Create beautiful Ganpati Bappa greeting cards."
    },
    {
        "name": "Onam",
        "slug": "onam",
        "religion_culture": "Hindu",
        "typical_month": "August-September",
        "description": "Onam is Kerala's harvest festival celebrating the homecoming of the mythical King Mahabali. It features elaborate feasts, boat races, and the famous flower carpet (Pookalam).",
        "story_history": "Onam commemorates the annual return of King Mahabali, a legendary ruler whose kingdom was so prosperous that the gods became jealous. Lord Vishnu, as Vamana, pushed Mahabali to the netherworld but granted him permission to visit his people once a year. Onam celebrates this reunion with great festivity.",
        "cultural_significance": "Onam represents Kerala's cultural identity, prosperity, and the memory of an ideal king who ensured equality and abundance. It transcends religious boundaries and is celebrated by all Keralites as a harvest thanksgiving.",
        "traditions": "Creating intricate Pookalam (flower rangoli), preparing Onasadya (elaborate vegetarian feast served on banana leaves), Vallam Kali (snake boat races), Pulikali (tiger dance), Kaikottikali (clap dance), and wearing traditional Kerala attire.",
        "seo_title": "Onam Wishes - Send Onam Greetings | FestWish",
        "seo_description": "Send warm Onam wishes to loved ones. Create beautiful harvest festival greeting cards."
    },
    {
        "name": "Pongal",
        "slug": "pongal",
        "religion_culture": "Hindu",
        "typical_month": "January",
        "description": "Pongal is Tamil Nadu's four-day harvest festival thanking the Sun God and farm animals. The name comes from the ceremonial dish of rice boiled in milk until it overflows.",
        "story_history": "Pongal has ancient Dravidian origins as a harvest thanksgiving. The festival celebrates the end of the winter solstice and the sun's northward journey. It honors the Sun God (Surya) for agricultural abundance and cattle that help in farming.",
        "cultural_significance": "Pongal represents gratitude for nature's bounty, agricultural prosperity, and the bond between humans and animals. It marks the beginning of the Tamil month Thai and the auspicious Uttarayan period.",
        "traditions": "Cooking Pongal rice in new pots until it overflows (symbolizing abundance), decorating cattle with flowers and bells, creating kolam designs, burning old items on Bhogi, offering prayers to the Sun God, and family gatherings.",
        "seo_title": "Pongal Wishes - Send Pongal Greetings | FestWish",
        "seo_description": "Send Happy Pongal wishes. Create beautiful harvest festival greeting cards."
    },
    {
        "name": "Baisakhi",
        "slug": "baisakhi",
        "religion_culture": "Sikh",
        "typical_month": "April",
        "description": "Baisakhi marks the Sikh New Year and the founding of the Khalsa by Guru Gobind Singh in 1699. It's also celebrated as a spring harvest festival in Punjab.",
        "story_history": "On Baisakhi 1699, Guru Gobind Singh Ji established the Khalsa, a community of saint-soldiers, at Anandpur Sahib. He asked for volunteers willing to sacrifice their lives, and five men (Panj Pyare) stepped forward. This act created the foundation of Sikh identity with the articles of faith (5 Ks).",
        "cultural_significance": "Baisakhi represents Sikh identity, courage, sacrifice, and the harvest celebration. It commemorates the birth of the Khalsa and the values of equality, service, and devotion that define Sikhism.",
        "traditions": "Visiting Gurdwaras for prayers and kirtan, Nagar Kirtan processions, performing Bhangra and Gidda dances, preparing festive meals, fairs and melas, and the ritual of Amrit Sanchar (baptism ceremony).",
        "seo_title": "Baisakhi Wishes - Send Vaisakhi Greetings | FestWish",
        "seo_description": "Send Happy Baisakhi wishes. Create beautiful Punjabi New Year greeting cards."
    },
    {
        "name": "Eid al-Adha",
        "slug": "eid-al-adha",
        "religion_culture": "Islamic",
        "typical_month": "Lunar Calendar",
        "description": "Eid al-Adha, the Festival of Sacrifice, honors Prophet Ibrahim's willingness to sacrifice his son as an act of obedience to God. It coincides with the Hajj pilgrimage.",
        "story_history": "The festival commemorates Prophet Ibrahim's (Abraham's) ultimate test of faith when God commanded him to sacrifice his son Ismail. As Ibrahim was about to comply, God intervened and provided a ram to sacrifice instead. This act of devotion and submission to God's will is honored annually.",
        "cultural_significance": "Eid al-Adha represents faith, sacrifice, obedience to God, and charity. It reminds Muslims of the importance of submission to Allah and caring for the less fortunate. The meat from sacrificed animals is distributed to family, friends, and the poor.",
        "traditions": "Performing Eid prayers, Qurbani (animal sacrifice), distributing meat to the needy, wearing new clothes, visiting family and friends, preparing special dishes, and giving gifts to children.",
        "seo_title": "Eid al-Adha Wishes - Send Bakrid Greetings | FestWish",
        "seo_description": "Send blessed Eid al-Adha wishes. Create beautiful Festival of Sacrifice greeting cards."
    },
    {
        "name": "Makar Sankranti",
        "slug": "makar-sankranti",
        "religion_culture": "Hindu",
        "typical_month": "January",
        "description": "Makar Sankranti marks the sun's transition into Capricorn (Makar) and the beginning of longer days. It's celebrated with kite flying, bonfires, and sesame-jaggery sweets.",
        "story_history": "The festival has astronomical significance marking the winter solstice and the sun's northward journey (Uttarayan). According to mythology, on this day, the Sun God visits his son Saturn (Shani), overcoming their estranged relationship. It's also associated with the end of winter and the harvest season.",
        "cultural_significance": "Makar Sankranti represents new beginnings, the triumph of light over darkness, and agricultural thanksgiving. It's one of the few Hindu festivals following the solar calendar, making its date (January 14-15) relatively fixed.",
        "traditions": "Flying colorful kites, preparing til-gul (sesame-jaggery) sweets, taking holy dips in rivers, bonfires (Lohri in Punjab), offering prayers to the Sun God, and exchanging greetings 'Til gul ghya, god god bola' (eat sweet and speak sweet).",
        "seo_title": "Makar Sankranti Wishes - Send Sankranti Greetings | FestWish",
        "seo_description": "Send Happy Makar Sankranti wishes. Create beautiful kite festival greeting cards."
    },
    {
        "name": "Lohri",
        "slug": "lohri",
        "religion_culture": "Punjabi",
        "typical_month": "January",
        "description": "Lohri is a Punjabi winter folk festival celebrating the harvest season and the end of winter's coldest days. It features bonfires, folk songs, and festive foods.",
        "story_history": "Lohri's origins are linked to Punjab's agricultural heritage and folklore about Dulla Bhatti, a folk hero who rescued girls from being sold by Mughal rulers. The songs sung around bonfires recount his brave deeds. It also celebrates the winter solstice and the return of longer days.",
        "cultural_significance": "Lohri represents the celebration of harvest, fertility, and the triumph of light over darkness. It's especially significant for newlyweds and families with newborns, marking important life transitions.",
        "traditions": "Lighting bonfires, throwing popcorn and rewri into the fire, singing Lohri folk songs, performing Bhangra and Gidda, eating sarson da saag and makki di roti, gajak, and distributing sweets.",
        "seo_title": "Lohri Wishes - Send Lohri Greetings | FestWish",
        "seo_description": "Send Happy Lohri wishes. Create beautiful Punjabi bonfire festival greeting cards."
    },
    {
        "name": "Dussehra",
        "slug": "dussehra",
        "religion_culture": "Hindu",
        "typical_month": "October",
        "description": "Dussehra (Vijayadashami) celebrates Lord Rama's victory over the demon king Ravana and Goddess Durga's triumph over Mahishasura. Effigies of Ravana are burned across India.",
        "story_history": "The festival marks two legendary victories: Lord Rama's defeat of the ten-headed demon king Ravana after a fierce battle in Lanka to rescue Sita, and Goddess Durga's slaying of the buffalo demon Mahishasura after nine nights of battle. Both stories symbolize the eternal triumph of good over evil.",
        "cultural_significance": "Dussehra represents the victory of dharma (righteousness) over adharma (evil), truth over falsehood, and light over darkness. It's a reminder that no matter how powerful evil becomes, good ultimately prevails.",
        "traditions": "Burning giant effigies of Ravana, Meghnath, and Kumbhakaran, Ram Lila performances depicting Ramayana, Durga idol immersion in Eastern India, exchanging apta leaves (symbolic gold), and seeking blessings from elders.",
        "seo_title": "Dussehra Wishes - Send Vijayadashami Greetings | FestWish",
        "seo_description": "Send Happy Dussehra wishes. Create beautiful victory over evil greeting cards."
    },
    {
        "name": "Karwa Chauth",
        "slug": "karwa-chauth",
        "religion_culture": "Hindu",
        "typical_month": "October-November",
        "description": "Karwa Chauth is a one-day festival where married women fast from sunrise to moonrise for the longevity and prosperity of their husbands.",
        "story_history": "The festival has roots in ancient times when women prayed for their husbands' safe return from wars and long journeys. The most popular legend involves Queen Veervati, whose brothers tricked her into breaking her fast early, causing her husband's death. Through devotion, she brought him back to life.",
        "cultural_significance": "Karwa Chauth represents marital love, devotion, and the sacred bond between husband and wife. In modern times, many couples observe mutual fasts, reflecting evolving gender dynamics while honoring the tradition.",
        "traditions": "Married women fasting without food or water, applying mehendi, wearing wedding finery, gathering to sing traditional songs, breaking the fast after sighting the moon through a sieve while looking at husband's face, and husbands giving gifts.",
        "seo_title": "Karwa Chauth Wishes - Send Karva Chauth Greetings | FestWish",
        "seo_description": "Send loving Karwa Chauth wishes. Create beautiful fasting festival greeting cards."
    },
    {
        "name": "Janmashtami",
        "slug": "janmashtami",
        "religion_culture": "Hindu",
        "typical_month": "August",
        "description": "Janmashtami celebrates the birth of Lord Krishna, the eighth avatar of Vishnu. Devotees fast, sing bhajans, and enact Krishna's playful childhood stories.",
        "story_history": "Lord Krishna was born at midnight in a prison cell in Mathura to Devaki and Vasudeva. His uncle King Kansa had imprisoned them after a prophecy that Devaki's eighth child would kill him. Vasudeva miraculously carried baby Krishna across the Yamuna river to safety in Gokul, where he was raised by Nanda and Yashoda.",
        "cultural_significance": "Janmashtami celebrates divine love, playfulness, and the victory of good over evil. Krishna's teachings in the Bhagavad Gita provide spiritual guidance. His life represents the importance of dharma, devotion, and divine intervention.",
        "traditions": "Fasting until midnight (Krishna's birth time), singing devotional bhajans, enacting Raas Leela, Dahi Handi (human pyramids to break butter pots), decorating Krishna idols, visiting temples, and offering 56 varieties of food (Chhappan Bhog).",
        "seo_title": "Janmashtami Wishes - Send Krishna Jayanti Greetings | FestWish",
        "seo_description": "Send blessed Janmashtami wishes. Create beautiful Lord Krishna birthday greeting cards."
    },
    {
        "name": "Chhath Puja",
        "slug": "chhath-puja",
        "religion_culture": "Hindu",
        "typical_month": "October-November",
        "description": "Chhath Puja is an ancient Hindu festival dedicated to the Sun God and his wife Usha. Devotees offer prayers standing in water bodies at sunrise and sunset.",
        "story_history": "Chhath Puja has Vedic origins, with rituals described in the Rig Veda. Legend connects it to Draupadi and the Pandavas who performed the ritual during their exile. Another story links it to Karna, the son of Surya (Sun God), who was blessed with extraordinary powers through sun worship.",
        "cultural_significance": "Chhath represents gratitude to the Sun for sustaining life on Earth and prayers for well-being. It's particularly significant in Bihar, Jharkhand, and Eastern Uttar Pradesh. The festival promotes environmental consciousness as it requires clean water bodies.",
        "traditions": "Nahay Khay (holy bath and eating), Lohanda and Kharna (fasting and preparing prasad), standing in water to offer arghya (offerings) to setting and rising sun, 36-hour fasting without water, and preparing thekua and other offerings.",
        "seo_title": "Chhath Puja Wishes - Send Chhath Greetings | FestWish",
        "seo_description": "Send auspicious Chhath Puja wishes. Create beautiful Sun worship greeting cards."
    },
    {
        "name": "Republic Day",
        "slug": "republic-day",
        "religion_culture": "Indian",
        "typical_month": "January",
        "description": "Republic Day celebrates the adoption of the Constitution of India on January 26, 1950, marking the transition to an independent republic with a democratic government.",
        "story_history": "On January 26, 1950, the Constitution of India came into effect, replacing the Government of India Act 1935. This date was chosen because it was on January 26, 1930, that the Indian National Congress proclaimed the Declaration of Indian Independence (Purna Swaraj). Dr. B.R. Ambedkar was the chief architect of the Indian Constitution.",
        "cultural_significance": "Republic Day honors India's sovereignty, democratic values, and the sacrifices of freedom fighters. It's a day to celebrate unity in diversity and recommit to the ideals of justice, liberty, equality, and fraternity enshrined in the Constitution.",
        "traditions": "Grand parade at Rajpath in New Delhi featuring military displays, cultural tableaux from states, fly-pasts, the unfurling of the national flag, the President taking the salute, Beating Retreat ceremony, and patriotic events in schools and communities.",
        "seo_title": "Republic Day Wishes - Send Patriotic Greetings | FestWish",
        "seo_description": "Send patriotic Republic Day wishes. Create beautiful greeting cards celebrating India's Constitution."
    },
    {
        "name": "Basant Panchami",
        "slug": "basant-panchami",
        "religion_culture": "Hindu",
        "typical_month": "January-February",
        "description": "Basant Panchami marks the arrival of spring and is dedicated to Goddess Saraswati, the deity of knowledge, music, and arts. Yellow is the dominant color of celebrations.",
        "story_history": "According to Hindu mythology, Lord Brahma created the universe but found it silent and dull. He created Goddess Saraswati, whose veena music brought life and speech to creation. Basant Panchami celebrates her birth and the onset of spring (Basant means spring).",
        "cultural_significance": "The festival represents the pursuit of knowledge, creativity, and wisdom. Students worship Saraswati for academic success. It marks the preparation for Holi, which comes 40 days later. The yellow color symbolizes prosperity and the mustard flowers blooming in spring.",
        "traditions": "Wearing yellow clothes, worshipping Goddess Saraswati, placing books and instruments near her idol, flying kites, eating yellow sweets like kesar halwa and boondi, and initiating children into learning (Vidya Arambham).",
        "seo_title": "Basant Panchami Wishes - Send Saraswati Puja Greetings | FestWish",
        "seo_description": "Send blessed Basant Panchami wishes. Create beautiful Saraswati Puja greeting cards."
    },
    {
        "name": "Mardi Gras",
        "slug": "mardi-gras",
        "religion_culture": "Christian",
        "typical_month": "February-March",
        "description": "Mardi Gras (Fat Tuesday) is a carnival celebration before the Christian season of Lent. New Orleans hosts the most famous American celebration with parades and festivities.",
        "story_history": "Mardi Gras has roots in medieval Europe as a last celebration before the fasting and penance of Lent. French explorers brought the tradition to America in the late 17th century. New Orleans held its first Mardi Gras parade in 1857, establishing the tradition of krewes (social organizations) hosting elaborate parades.",
        "cultural_significance": "Mardi Gras represents indulgence before sacrifice, community celebration, and cultural expression. It's a time for revelry, creativity, and the blending of French, African, and American traditions in cities like New Orleans.",
        "traditions": "Colorful parades with elaborate floats, wearing masks and costumes, throwing and catching beads, eating King Cake, jazz music and dancing, the colors purple (justice), gold (power), and green (faith), and the cry 'Laissez les bons temps rouler!' (Let the good times roll!).",
        "seo_title": "Mardi Gras Wishes - Send Carnival Greetings | FestWish",
        "seo_description": "Send festive Mardi Gras wishes. Create beautiful carnival greeting cards."
    },
    {
        "name": "Ram Navami",
        "slug": "ram-navami",
        "religion_culture": "Hindu",
        "typical_month": "March-April",
        "description": "Ram Navami celebrates the birth of Lord Rama, the seventh avatar of Vishnu and hero of the epic Ramayana. It falls on the ninth day of Chaitra Navratri.",
        "story_history": "Lord Rama was born to King Dasharatha and Queen Kaushalya of Ayodhya on the ninth day of the bright fortnight of Chaitra month. His birth was divine, meant to destroy the demon king Ravana. Rama's life exemplifies dharma (righteousness), and he's revered as Maryada Purushottam (the ideal man).",
        "cultural_significance": "Ram Navami celebrates ideal virtues: honor, courage, devotion to duty, and righteous conduct. Rama's life teaches the importance of keeping promises, respecting elders, and standing for truth even at great personal cost.",
        "traditions": "Reading and reciting the Ramayana, visiting Ram temples, performing pujas with flowers and fruits, fasting, chariot processions (Rath Yatras), community feasts, and charitable acts.",
        "seo_title": "Ram Navami Wishes - Send Sri Rama Greetings | FestWish",
        "seo_description": "Send blessed Ram Navami wishes. Create beautiful Lord Rama birthday greeting cards."
    },
    {
        "name": "Nowruz",
        "slug": "nowruz",
        "religion_culture": "Persian",
        "typical_month": "March",
        "description": "Nowruz (Persian New Year) marks the first day of spring and the beginning of the year in the Persian calendar. Celebrated for over 3,000 years across Central Asia and beyond.",
        "story_history": "Nowruz dates back to ancient Zoroastrian traditions, celebrating the victory of light over darkness and the renewal of nature. The legendary King Jamshid is credited with establishing the festival. UNESCO recognizes Nowruz as an Intangible Cultural Heritage of Humanity.",
        "cultural_significance": "Nowruz represents renewal, rebirth, and the triumph of good over evil. It emphasizes family unity, forgiveness, and starting fresh. The spring equinox timing connects it to nature's awakening and new beginnings.",
        "traditions": "Setting up Haft-sin table with seven symbolic items starting with 'S', spring cleaning (khouneh tekouni), jumping over bonfires (Chaharshanbe Suri), visiting elders, exchanging gifts, and the 13-day celebration ending with Sizdah Bedar (nature day).",
        "seo_title": "Nowruz Wishes - Send Persian New Year Greetings | FestWish",
        "seo_description": "Send warm Nowruz wishes. Create beautiful Persian New Year greeting cards."
    },
    {
        "name": "Ugadi",
        "slug": "ugadi",
        "religion_culture": "Hindu",
        "typical_month": "March-April",
        "description": "Ugadi (also Gudi Padwa in Maharashtra) marks the New Year for people in the Deccan region of India. It falls on the first day of Chaitra month.",
        "story_history": "According to Hindu mythology, Lord Brahma began creation on this day. The word 'Ugadi' comes from 'Yuga' (era) and 'Adi' (beginning). In Maharashtra, the festival commemorates the victories of the Maratha warrior king Chhatrapati Shivaji.",
        "cultural_significance": "Ugadi represents new beginnings, hope, and prosperity. It's a time to shed the old and embrace the new, both materially and spiritually. The festival marks the beginning of the Hindu lunisolar calendar.",
        "traditions": "Raising Gudi (decorated pole with cloth and pot) in Maharashtra, preparing Ugadi Pachadi (dish with six tastes representing life's experiences), decorating homes with mango leaves, wearing new clothes, oil baths, and visiting temples.",
        "seo_title": "Ugadi Wishes - Send Gudi Padwa Greetings | FestWish",
        "seo_description": "Send Happy Ugadi and Gudi Padwa wishes. Create beautiful New Year greeting cards."
    },
    {
        "name": "Good Friday",
        "slug": "good-friday",
        "religion_culture": "Christian",
        "typical_month": "March-April",
        "description": "Good Friday commemorates the crucifixion and death of Jesus Christ at Calvary. It's observed with solemnity, fasting, and prayer during Holy Week before Easter.",
        "story_history": "According to the Gospels, Jesus was arrested, tried, and sentenced to death by crucifixion under Pontius Pilate. He carried his cross to Golgotha where he was crucified between two criminals. Christians believe his death was a sacrifice for humanity's sins.",
        "cultural_significance": "Good Friday represents sacrifice, redemption, and the depth of divine love. It's a day for reflection on suffering, mortality, and the hope of resurrection. The term 'Good' likely derives from 'God's Friday' or refers to the good that came from Jesus's sacrifice.",
        "traditions": "Church services including Stations of the Cross, veneration of the cross, reading the Passion narrative, fasting and abstaining from meat, wearing black or somber clothing, hot cross buns, and periods of silence and reflection.",
        "seo_title": "Good Friday Messages - Send Solemn Greetings | FestWish",
        "seo_description": "Send thoughtful Good Friday messages. Create meaningful greeting cards for Holy Week."
    },
    {
        "name": "Buddha Purnima",
        "slug": "buddha-purnima",
        "religion_culture": "Buddhist",
        "typical_month": "April-May",
        "description": "Buddha Purnima (Vesak) celebrates the birth, enlightenment, and death of Gautama Buddha, all believed to have occurred on the same day of different years.",
        "story_history": "Siddhartha Gautama was born in Lumbini (Nepal) around 563 BCE to Queen Maya and King Suddhodana. After years of spiritual seeking, he attained enlightenment under the Bodhi tree in Bodh Gaya. He passed away (attained Parinirvana) at age 80 in Kushinagar.",
        "cultural_significance": "Buddha Purnima celebrates the teachings of compassion, non-violence, and the path to enlightenment. It reminds followers of the possibility of achieving nirvana through right living, meditation, and wisdom.",
        "traditions": "Visiting Buddhist temples, meditating, chanting sutras, offering flowers, candles and incense to Buddha statues, giving alms to monks, releasing caged birds symbolizing liberation, and practicing acts of kindness.",
        "seo_title": "Buddha Purnima Wishes - Send Vesak Greetings | FestWish",
        "seo_description": "Send peaceful Buddha Purnima wishes. Create beautiful Vesak greeting cards."
    },
    {
        "name": "Rath Yatra",
        "slug": "rath-yatra",
        "religion_culture": "Hindu",
        "typical_month": "June-July",
        "description": "Rath Yatra is the annual chariot festival of Lord Jagannath in Puri, Odisha. Massive wooden chariots carrying the deities are pulled through the streets by devotees.",
        "story_history": "The festival commemorates Lord Krishna's journey from Gokul to Mathura. In Puri, it represents Lord Jagannath's annual visit to his birthplace at the Gundicha Temple. The tradition has been celebrated for centuries and is mentioned in ancient Hindu texts.",
        "cultural_significance": "Rath Yatra symbolizes the lord's accessibility to all devotees regardless of caste or status. The English word 'juggernaut' derives from Jagannath, reflecting the unstoppable nature of the massive chariots. It represents divine grace reaching out to devotees.",
        "traditions": "Building three enormous chariots for Jagannath, Balabhadra, and Subhadra, pulling the chariots with thick ropes, millions of pilgrims gathering in Puri, offering Mahaprasad (sacred food), and the return journey (Bahuda Yatra).",
        "seo_title": "Rath Yatra Wishes - Send Jagannath Greetings | FestWish",
        "seo_description": "Send blessed Rath Yatra wishes. Create beautiful Jagannath Puri greeting cards."
    },
    {
        "name": "Guru Purnima",
        "slug": "guru-purnima",
        "religion_culture": "Hindu",
        "typical_month": "July",
        "description": "Guru Purnima honors spiritual and academic teachers. Celebrated on the full moon day of Ashadha month, it's dedicated to the sage Vyasa who classified the Vedas.",
        "story_history": "The day commemorates the sage Vyasa, who is credited with compiling the Vedas, writing the Mahabharata, and composing the Puranas. It's also believed that Lord Shiva became the first guru (Adi Guru) on this day, teaching yoga to the Saptarishis.",
        "cultural_significance": "Guru Purnima celebrates the guru-shishya (teacher-student) tradition central to Indian spirituality. It acknowledges that enlightenment comes through guidance, and teachers who illuminate the path of knowledge deserve reverence.",
        "traditions": "Offering prayers and gifts to teachers, performing Guru Puja, reading scriptures, meditating, fasting, visiting ashrams, and expressing gratitude to all who have guided one's learning journey.",
        "seo_title": "Guru Purnima Wishes - Send Teacher's Day Greetings | FestWish",
        "seo_description": "Send respectful Guru Purnima wishes. Create beautiful greeting cards honoring teachers."
    },
    {
        "name": "Independence Day",
        "slug": "independence-day-india",
        "religion_culture": "Indian",
        "typical_month": "August",
        "description": "Independence Day celebrates India's freedom from British colonial rule on August 15, 1947. It's a national holiday marked by flag hoisting and patriotic events.",
        "story_history": "After nearly 200 years of British rule and decades of struggle led by Mahatma Gandhi, Jawaharlal Nehru, and countless freedom fighters, India gained independence at midnight on August 15, 1947. Nehru's famous 'Tryst with Destiny' speech marked the historic moment.",
        "cultural_significance": "Independence Day honors the sacrifices of freedom fighters and celebrates India's sovereignty. It's a day to reflect on national unity, democratic values, and the ongoing journey of nation-building.",
        "traditions": "Flag hoisting ceremonies, the Prime Minister's address from Red Fort, patriotic songs and cultural programs, kite flying, wearing tricolor clothing, school and community events, and remembering freedom fighters.",
        "seo_title": "Independence Day Wishes - Send Patriotic Greetings | FestWish",
        "seo_description": "Send patriotic Independence Day wishes. Create beautiful freedom celebration greeting cards."
    },
    {
        "name": "Mid-Autumn Festival",
        "slug": "mid-autumn-festival",
        "religion_culture": "Chinese",
        "typical_month": "September-October",
        "description": "The Mid-Autumn Festival (Moon Festival) celebrates the harvest moon with family reunions, moon gazing, and eating mooncakes. It's one of China's most important festivals.",
        "story_history": "The festival dates back over 3,000 years to moon worship in ancient China. The most famous legend involves Chang'e, who swallowed an immortality elixir and floated to the moon, where she lives with a jade rabbit. Her husband Houyi created mooncakes to remember her.",
        "cultural_significance": "The Mid-Autumn Festival celebrates family unity, harvest abundance, and the full moon as a symbol of completeness and reunion. The round shape of mooncakes represents family togetherness.",
        "traditions": "Eating mooncakes with various fillings, lighting colorful lanterns, moon gazing, family reunions and dinners, telling the legend of Chang'e, drinking osmanthus wine, and performing dragon and lion dances.",
        "seo_title": "Mid-Autumn Festival Wishes - Send Moon Festival Greetings | FestWish",
        "seo_description": "Send warm Mid-Autumn Festival wishes. Create beautiful Moon Festival greeting cards."
    },
    {
        "name": "Halloween",
        "slug": "halloween",
        "religion_culture": "Western",
        "typical_month": "October",
        "description": "Halloween is celebrated on October 31st with costumes, trick-or-treating, jack-o'-lanterns, and spooky decorations. It blends ancient Celtic traditions with modern festivities.",
        "story_history": "Halloween originated from the ancient Celtic festival of Samhain, when people believed the boundary between the living and dead became thin. They lit bonfires and wore costumes to ward off ghosts. Christian influences transformed it into All Hallows' Eve, preceding All Saints' Day.",
        "cultural_significance": "Halloween represents the celebration of mystery, imagination, and the supernatural. It's a time for playful scares, community gatherings, and creative expression through costumes and decorations.",
        "traditions": "Wearing costumes, trick-or-treating for candy, carving jack-o'-lanterns from pumpkins, haunted houses, costume parties, apple bobbing, telling ghost stories, and decorating with spiders, bats, and skeletons.",
        "seo_title": "Halloween Wishes - Send Spooky Greetings | FestWish",
        "seo_description": "Send fun Halloween wishes. Create spooky and creative Halloween greeting cards."
    },
    {
        "name": "Bhai Dooj",
        "slug": "bhai-dooj",
        "religion_culture": "Hindu",
        "typical_month": "October-November",
        "description": "Bhai Dooj celebrates the bond between brothers and sisters, observed two days after Diwali. Sisters pray for their brothers' well-being and apply tilak on their foreheads.",
        "story_history": "The festival has several origins. One legend says Yama (god of death) visited his sister Yamuna on this day, who welcomed him with tilak and sweets. Yamuna asked Yama to grant immortality to brothers visited by sisters on this day. Another story connects it to Lord Krishna visiting his sister Subhadra after defeating Narakasura.",
        "cultural_significance": "Bhai Dooj reinforces the sibling bond and family values. Unlike Raksha Bandhan where brothers pledge protection, Bhai Dooj focuses on sisters' blessings and prayers for brothers' prosperity and long life.",
        "traditions": "Sisters applying tilak on brothers' foreheads, brothers giving gifts and money, performing aarti, preparing special meals, sisters praying at Yamuna river, and family gatherings.",
        "seo_title": "Bhai Dooj Wishes - Send Sibling Greetings | FestWish",
        "seo_description": "Send loving Bhai Dooj wishes. Create beautiful brother-sister greeting cards."
    },
    {
        "name": "Kwanzaa",
        "slug": "kwanzaa",
        "religion_culture": "African-American",
        "typical_month": "December",
        "description": "Kwanzaa is a week-long celebration honoring African heritage and culture, observed from December 26 to January 1. Each day focuses on one of seven core principles.",
        "story_history": "Kwanzaa was created in 1966 by Dr. Maulana Karenga as a way for African Americans to celebrate their heritage. The name comes from the Swahili phrase 'matunda ya kwanza' meaning 'first fruits.' It was inspired by African harvest celebrations.",
        "cultural_significance": "Kwanzaa celebrates African culture, community, and family. The seven principles (Nguzo Saba) are: Umoja (Unity), Kujichagulia (Self-Determination), Ujima (Collective Work), Ujamaa (Cooperative Economics), Nia (Purpose), Kuumba (Creativity), and Imani (Faith).",
        "traditions": "Lighting the kinara (candle holder) with seven candles, discussing the daily principle, giving handmade gifts (zawadi), the Karamu feast on December 31, wearing African clothing, decorating with African art, and pouring libations for ancestors.",
        "seo_title": "Kwanzaa Wishes - Send Cultural Greetings | FestWish",
        "seo_description": "Send meaningful Kwanzaa wishes. Create beautiful African heritage celebration cards."
    },
    {
        "name": "Obon",
        "slug": "obon",
        "religion_culture": "Japanese",
        "typical_month": "August",
        "description": "Obon (Bon Festival) is a Japanese Buddhist tradition honoring ancestral spirits. Families reunite, visit graves, and perform traditional dances to welcome departed souls.",
        "story_history": "Obon originates from the Buddhist story of Maudgalyayana, a disciple of Buddha who used his powers to see his deceased mother suffering in the Realm of Hungry Ghosts. Buddha instructed him to make offerings to monks, which freed her spirit. His joy led to the first Bon dance.",
        "cultural_significance": "Obon represents gratitude to ancestors and the interconnection of generations. It's one of Japan's most important family reunions, similar to Thanksgiving in spirit, when millions return to their hometowns.",
        "traditions": "Cleaning family graves (ohaka mairi), setting up altars with offerings, floating paper lanterns on rivers (toro nagashi), performing Bon Odori dances, family gatherings, and preparing special foods.",
        "seo_title": "Obon Wishes - Send Bon Festival Greetings | FestWish",
        "seo_description": "Send thoughtful Obon wishes. Create beautiful Bon Festival greeting cards."
    },
    {
        "name": "Songkran",
        "slug": "songkran",
        "religion_culture": "Thai",
        "typical_month": "April",
        "description": "Songkran is the Thai New Year celebrated with the world's biggest water fight. The three-day festival marks the traditional solar new year in Thailand and Southeast Asia.",
        "story_history": "Songkran has ancient roots in Hindu-Buddhist traditions marking the sun's entry into Aries. Originally a gentle ritual of pouring water on Buddha images and elders' hands, it evolved into massive water battles. The name comes from the Sanskrit word for 'passage' or 'transformation.'",
        "cultural_significance": "Songkran represents purification, paying respect to elders, and washing away the past year's misfortunes. Water symbolizes cleansing and renewal. It's a time for family reunions and merit-making at temples.",
        "traditions": "Massive water fights with water guns and buckets, pouring scented water on Buddha statues, gentle water pouring on elders' hands, visiting temples, building sand stupas, releasing caged birds, and traditional Thai games.",
        "seo_title": "Songkran Wishes - Send Thai New Year Greetings | FestWish",
        "seo_description": "Send Happy Songkran wishes. Create beautiful Thai New Year greeting cards."
    },
    {
        "name": "Losar",
        "slug": "losar",
        "religion_culture": "Tibetan",
        "typical_month": "February",
        "description": "Losar is the Tibetan New Year, a 15-day celebration featuring religious ceremonies, cultural performances, and family gatherings. It's the most important Tibetan festival.",
        "story_history": "Losar predates Buddhism in Tibet, originating as a winter incense-burning ceremony. When Buddhism arrived, religious elements were incorporated. The current form developed in the 14th century. The celebration begins on the new moon of the first Tibetan month.",
        "cultural_significance": "Losar represents renewal, purification, and the continuation of Tibetan Buddhist culture. It's a time for spiritual reflection, family unity, and preserving traditions, especially significant for Tibetans in exile.",
        "traditions": "Cleaning homes to sweep away bad luck, making khapse (fried cookies), preparing guthuk soup with symbolic items, hanging prayer flags, visiting monasteries, exchanging gifts, performing Cham dances, and setting off firecrackers.",
        "seo_title": "Losar Wishes - Send Tibetan New Year Greetings | FestWish",
        "seo_description": "Send Tashi Delek Losar wishes. Create beautiful Tibetan New Year greeting cards."
    }
]
